module.exports = {
    ra: {
      action: {
        add_filter: "Přidat filter",
        add: "Přidat",
        back: "Zpět",
        bulk_actions: "1 položka vybrána |||| %{smart_count} položky vybrány",
        cancel: "Zrušit",
        clear_input_value: "Smazat hodnotu",
        clone: "Klonovat",
        confirm: "Potvrdit",
        create: "Vytvořit",
        delete: "Smazat",
        edit: "Editovat",
        export: "Exportovat",
        list: "Listovat",
        refresh: "Obnovit",
        remove_filter: "Smazat filtr",
        remove: "Smazat",
        save: "Uložit",
        search: "Hledat",
        show: "Ukázat",
        sort: "Řadit",
        undo: "Vrátit",
        unselect: "Odznačit",
        expand: "Rozšířit",
        close: "Zavřít",
        open_menu: "Otevřít menu",
        close_menu: "Zavřit menu",
      },
      boolean: {
        true: "Ano",
        false: "Ne",
        null: " ",
      },
      page: {
        create: "Vytvořit %{name}",
        dashboard: "Rozcestník",
        edit: "%{name} #%{id}",
        error: "Něco se pokazilo",
        list: "%{name}",
        loading: "Nahrávám",
        not_found: "Nenalezeno",
        show: "%{name} #%{id}",
        empty: "Neznámý %{name}.",
        invite: "Chcete 1 přidat?",
      },
      input: {
        file: {
          upload_several:
            "Pro upload zde pusťte soubory nebo klikněte pro výběr.",
          upload_single:
            "Pro upload zde pusťte soubor nebo klikněte pro výběr.",
        },
        image: {
          upload_several:
            "Pro upload zde pusťte obrázky nebo klikněte pro výběr.",
          upload_single:
            "Pro upload zde pusťte obrázek nebo klikněte pro výběr.",
        },
        references: {
          all_missing: "Nenalezeny reference",
          many_missing: "Alespoň 1 reference nenalezena.",
          single_missing: "Přidružené reference není dostupná.",
        },
        password: {
          toggle_visible: "Skrýt heslo",
          toggle_hidden: "Ukázat heslo",
        },
      },
      message: {
        about: "O",
        are_you_sure: "Jste si jistí?",
        bulk_delete_content:
          "Jste si jistí, že chcete smazat tuto %{name} položku? |||| Jste si jistí, že chcete smazat tyto %{smart_count} položky?",
        bulk_delete_title: "Smazat %{name} |||| Smazat %{smart_count} %{name}",
        delete_content: "Jste si jistí, že chcete smazat tuto položku?",
        delete_title: "Smazat %{name} #%{id}",
        details: "Detaily",
        error: "Nastala chyba klientská a požadavek nebyl dokončen.",
        invalid_form: "Formulář není validní. Prosím zkontrolujte chyby",
        loading: "Stránka se načítá, vyčkejte prosím",
        no: "Ne",
        not_found:
          "Buď jste napsal špatné URL, nebo jste otevřel špatný odkaz.",
        yes: "Ano",
        unsaved_changes:
          "Některé vaše změny nebyly uloženy. Jste si jistí, že je chcete ignorovat?",
      },
      navigation: {
        no_results: "Nenalezeny žádné výsledky",
        no_more_results:
          "Stránka číslo %{page} je mimo rozpětí. Zkuste předchozí stránku.",
        page_out_of_boundaries: "Stránka číslo %{page} je mimo rozpětí",
        page_out_from_end: "Není možné jít za poslední stránku",
        page_out_from_begin: "Není možné jít před stránku 1",
        page_range_info: "%{offsetBegin}-%{offsetEnd} z %{total}",
        page_rows_per_page: "Řádky na stránce:",
        next: "Další",
        prev: "Předchozí",
        skip_nav: "Přeskočit na obsah",
      },
      sort: {
        sort_by: "Seřadit podle %{field} %{order}",
        ASC: "vzestupně",
        DESC: "sestupně",
      },
      auth: {
        auth_check_error: "Pro pokračování se prosím přihlašte",
        user_menu: "Profil",
        username: "Uživatelské jméno",
        password: "Heslo",
        sign_in: "Přihlásit",
        sign_in_error: "Přihlášení selhalo, prosím opakujte",
        logout: "Odhlásit",
      },
      notification: {
        updated: "Prvek upraven |||| %{smart_count} prvků upraveno",
        created: "Prvek vytvořen",
        deleted: "Prvek smazán |||| %{smart_count} prvků smazáno",
        bad_item: "Špatný prvek",
        item_doesnt_exist: "Prvek neexistuje",
        http_error: "Komunikační chyba serveru",
        data_provider_error:
          "chyba poskytovatele dat. Pro detaily zkontrolujte konzoli.",
        i18n_error: "Není možné načíst překlad pro specifický jazyk",
        canceled: "Akce zrušena",
        logged_out: "Vaše sezení skončilo, prosím přepojte se.",
      },
      validation: {
        required: "Vyžadováno",
        minLength: "Musí být alespoň %{min} znaků",
        maxLength: "Musí být %{max} znaků nebo méně",
        minValue: "Musí být alespoň %{min}",
        maxValue: "musí být %{max} nebo méně",
        number: "Musí být číslo",
        email: "Musí být validní email",
        oneOf: "Musí být jeden z: %{options}",
        regex: "Musí odpovídat specifickému formátu (regexp): %{pattern}",
      },
    },
};
