import { TranslationMessages } from 'ra-core';

const czechMessages: TranslationMessages = {
    ra: {
        action: {
            add: 'Přidat',
            add_filter: 'Přidat filtr',
            back: 'Jít zpět',
            bulk_actions: '%{smart_count} položka vybrána |||| %{smart_count} položky vybrány |||| %{smart_count} položek vybráno',
            cancel: 'Zrušit',
            clear_array_input: 'Vymazat seznam',
            clear_input_value: 'Smazat hodnotu',
            clone: 'Klonovat',
            close: 'Zavřít',
            close_menu: 'Zavřít menu',
            confirm: 'Potvrdit',
            create: 'Vytvořit',
            create_item: 'Vytvořit',
            delete: 'Smazat',
            edit: 'Upravit',
            expand: 'Rozbalit',
            export: 'Exportovat',
            list: 'Listovat',
            move_down: 'Dolů',
            move_up: 'Nahoru',
            open: 'Otevřít',
            open_menu: 'Otevřít menu',
            refresh: 'Obnovit',
            remove: 'Odstranit',
            remove_all_filters: 'Odstranit všechny filtry',
            remove_filter: 'Odstranit filtr',
            save: 'Uložit',
            search: 'Hledat',
            select_all: 'Vybrat vše',
            select_all_button: 'Vybrat vše',
            select_columns: 'Sloupce',
            select_row: 'Vybrat řádek',
            show: 'Zobrazit',
            sort: 'Seřadit',
            toggle_theme: 'Přepnout téma',
            undo: 'Vrátit',
            unselect: 'Zrušit výběr',
            update: 'Aktualizovat',
            update_application: 'Znovu načíst aplikaci',
        },
        auth: {
            auth_check_error: 'Pro pokračování se prosím přihlaste',
            email: 'Email',
            logout: 'Odhlásit se',
            password: 'Heslo',
            sign_in: 'Přihlásit se',
            sign_in_error: 'Ověření selhalo, zkuste to znovu',
            user_menu: 'Profil',
            username: 'Uživatelské jméno',
        },
        boolean: {
            false: 'Ne',
            null: ' ',
            true: 'Ano',
        },
        configurable: {
            configureMode: 'Konfigurovat tuto stránku',
            customize: 'Přizpůsobit',
            Datagrid: {
                title: 'Datová mřížka',
                unlabeled: 'Neoznačený sloupec #%{column}',
            },
            inspector: {
                content: 'Pro konfiguraci UI elementů aplikace na ně najeďte myší',
                hideAll: 'Skrýt vše',
                reset: 'Resetovat nastavení',
                showAll: 'Zobrazit vše',
                title: 'Inspektor',
            },
            SimpleForm: {
                title: 'Formulář',
                unlabeled: 'Nepojmenovaný vstup #%{input}',
            },
            SimpleList: {
                primaryText: 'Primární text',
                secondaryText: 'Sekundární text',
                tertiaryText: 'Terciární text',
                title: 'Seznam',
            },
        },
        input: {
            file: {
                upload_several: 'Přetáhněte soubory pro nahrání nebo klikněte pro výběr',
                upload_single: 'Přetáhněte soubor pro nahrání nebo klikněte pro jeho výběr',
            },
            image: {
                upload_several: 'Přetáhněte obrázky pro nahrání nebo klikněte pro výběr',
                upload_single: 'Přetáhněte obrázek pro nahrání nebo klikněte pro jeho výběr',
            },
            password: {
                toggle_hidden: 'Zobrazit heslo',
                toggle_visible: 'Skrýt heslo',
            },
            references: {
                all_missing: 'Nelze nalézt referencovaná data',
                many_missing: 'Minimálně jedna z referencí se nezdá býti nadále dostupná',
                single_missing: 'Reference se nezdá býti nadále dostupná.',
            },
        },
        message: {
            about: 'O',
            access_denied: 'Nemáte potřebná oprávnění pro přístup na tuto stránku',
            are_you_sure: 'Jste si jistí?',
            auth_error: 'Při ověřování autentizačního tokenu došlo k chybě.',
            authentication_error: 'Server pro ověření vrátil chybu a vaše přihlašovací údaje nemohly být ověřeny.',
            bulk_delete_content: 'Jste si jistí, že chcete smazat %{name}? |||| Jste si jistí, že chcete smazat tyto %{smart_count} položky? |||| Jste si jistí, že chcete smazat těchto %{smart_count} položek?',
            bulk_delete_title: 'Smazat %{name} |||| Smazat %{smart_count} %{name} položky |||| Smazat %{smart_count} %{name} položek',
            bulk_update_content: 'Hromadně změnit obsah',
            bulk_update_title: 'Hromadně změnit titulek',
            clear_array_input: 'Opravdu chcete vymazat celý seznam?',
            delete_content: 'Jste si jistí, že chcete smazat tuto položku?',
            delete_title: 'Smazat %{name} #%{id}',
            details: 'Podrobnosti',
            error: 'Nastala chyba a váš požadavek nemohl být zpracován.',
            invalid_form: 'Formulář není validní. Prosím zkontrolujte chyby.',
            loading: 'Stránka se načítá, prosím strpení',
            no: 'Ne',
            not_found: 'Nic nebylo nalezeno.',
            placeholder_data_warning: 'Problém se sítí: Obnovení dat selhalo.',
            select_all_limit_reached: 'Je příliš mnoho prvků k výběru všech. Bylo vybráno pouze prvních %{max} prvků.',
            unsaved_changes: 'Některé změny nebyly uloženy. Chcete je ignorovat?',
            yes: 'Ano',
        },
        navigation: {
            clear_filters: 'Vymazat filtry',
            current_page: 'Stránka %{page}',
            first: 'První stránka',
            last: 'Poslední stránka',
            next: 'Další',
            no_filtered_results: 'Nenalezeny žádné %{name} s aktuálními filtry.',
            no_more_results: 'Stránka číslo %{page} je mimo rozsah. Zkuste předchozí.',
            no_results: 'Žádné výsledky nenalezeny',
            page: 'Jít na stránku %{page}',
            page_out_from_begin: 'Nelze se přepnout před první stránku',
            page_out_from_end: 'Nelze se přepnout za poslední stránkou',
            page_out_of_boundaries: 'Stránka číslo %{page} je mimo rozsah',
            page_range_info: '%{offsetBegin}-%{offsetEnd} z %{total}',
            page_rows_per_page: 'Záznamů na stránku: ',
            partial_page_range_info: '%{offsetBegin}-%{offsetEnd} z víc než %{offsetEnd}',
            previous: 'Předchozí',
            skip_nav: 'Přeskočit na obsah',
        },
        notification: {
            application_update_available: 'Je dostupná nová verze.',
            bad_item: 'Špatná položka',
            canceled: 'Akce zrušena',
            created: 'Položka vytvořena',
            data_provider_error: 'Chyba dataProvider komponenty. Pro více detailů zkontrolujte konzoli prohlížeče.',
            deleted: 'Položka smazána |||| %{smart_count} položky smazány |||| %{smart_count} položek smazáno',
            http_error: 'Chyba komunikace serveru',
            i18n_error: 'Nelze načíst překlady pro vybraný jazyk',
            item_doesnt_exist: 'Položka neexistuje',
            logged_out: 'Relace ukončena',
            not_authorized: 'Nemáte oprávnění k přístupu.',
            updated: 'Položka aktualizována |||| %{smart_count} položky aktualizovány |||| %{smart_count} položek aktualizováno',
        },
        page: {
            access_denied: 'Přístup odepřen',
            authentication_error: 'Chyba ověření',
            create: 'Vytvořit %{name}',
            dashboard: 'Nástěnka',
            edit: '%{name} #%{id}',
            empty: 'Zatím žádný %{name}',
            error: 'Něco se pokazilo',
            invite: 'Chcete přidat?',
            list: '%{name}',
            loading: 'Načítání',
            not_found: 'Nenalezeno',
            show: '%{name} #%{id}',
        },
        saved_queries: {
            help: 'Vyfiltrovat seznam a uložit tento dotaz na později',
            label: 'Uložené dotazy',
            new_dialog_title: 'Uložit aktuální dotaz jako',
            new_label: 'Uložit aktuální dotaz...',
            query_name: 'Jméno dotazu',
            remove_dialog_title: 'Odstranit uložený dotaz?',
            remove_label: 'Odstranit uložený dotaz',
            remove_label_with_name: 'Odstranit dotaz "%{name}"',
            remove_message: 'Jste si jistí, že chcete odstranit tuto položku z vašeho seznamu uložených dotazů?',
        },
        sort: {
            ASC: 'vzestupně',
            DESC: 'sestupně',
            sort_by: 'Seřadit podle %{field} %{order}',
        },
        validation: {
            email: 'Musí být validní emailová adresa',
            maxLength: 'Může obsahovat maximálně %{max} znaků',
            maxValue: 'Múže být maximálně %{max}',
            minLength: 'Musí obsahovat nejméně %{min} znaků',
            minValue: 'Musí být minimálně %{min}',
            number: 'Musí být číslo',
            oneOf: 'Musí splňovat jedno z: %{options}',
            regex: 'Musí být ve specifickém formátu (regexp): %{pattern}',
            required: 'Povinné pole',
            unique: 'Musí být jedinečné',
        },
    },
};

export default czechMessages;
